# Generated by Django 4.0.3 on 2022-03-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(height_field=300, upload_to='', width_field=200)),
            ],
        ),
    ]
