# Generated by Django 4.0.3 on 2022-03-24 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_fact_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fact',
            name='category',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Fact',
        ),
    ]
