# Generated by Django 4.0.3 on 2022-04-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_book_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='buy_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
