# Generated by Django 4.0.3 on 2022-04-13 11:56

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#696969', 'grey'), ('#0476D0', 'blue'), ('#2BB02B', 'green'), ('#FFA500', 'orange'), ('#5A4FCF', 'purple'), ('#E32227', 'red')], default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
