# Generated by Django 4.0.3 on 2022-04-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='populartiy',
            field=models.IntegerField(default=0),
        ),
    ]
