# Generated by Django 4.0.3 on 2022-04-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_remove_book_populartiy'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
