# Generated by Django 4.0.3 on 2022-04-15 15:28

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_book_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#696969', 'grey'), ('#0E61CB', 'blue'), ('#5F9834', 'green'), ('#FF8300', 'orange'), ('#5A4FCF', 'purple'), ('#FF4500', 'red'), ('#FC3C80', 'pink')], default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
