# Generated by Django 4.0.3 on 2022-04-16 12:39

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0022_alter_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#696969', 'Architecture'), ('#0E61CB', 'General'), ('#5F9834', 'Literature'), ('#FF8300', 'Cuisine'), ('#5A4FCF', 'Culture'), ('#FF4500', 'History'), ('#FC3C80', 'Book reviews')], default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
