# Generated by Django 4.0.3 on 2022-04-19 12:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_alter_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favourited_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
