# Generated by Django 4.0.3 on 2022-04-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_book_favourited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='favourited_by',
        ),
    ]
