# Generated by Django 4.0.3 on 2022-04-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_book_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quote',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
