# Generated by Django 4.0.3 on 2022-04-13 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
