# Generated by Django 4.0.3 on 2022-04-14 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_book_popularity'),
        ('articles', '0005_alter_article_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='related_book',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='books.book'),
        ),
    ]
