# Generated by Django 4.0.3 on 2022-05-19 10:14

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_article_image_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
