# Generated by Django 4.0.3 on 2022-05-19 14:23

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=s3direct.fields.S3DirectField(),
        ),
    ]
