# Generated by Django 4.0.3 on 2022-05-31 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_remove_book_price_alter_book_category_and_more'),
        ('articles', '0017_alter_article_image_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='books.category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.FileField(upload_to='media/articles/'),
        ),
    ]
