# Generated by Django 4.0.3 on 2022-04-20 13:17

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
