# Generated by Django 4.0.3 on 2022-04-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_profile_reading_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
